# -*- coding: utf-8 -*-
"""Currency_converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4I9sRAh_aRQiKw7n3LkwTiqp2ly4Kbl
"""

pip install forex-python

from forex_python.converter import CurrencyRates

def convert_currency(amount, from_currency, to_currency):
    c = CurrencyRates()

    try:
        exchange_rate = c.get_rate(from_currency, to_currency)
        converted_amount = amount * exchange_rate
        return converted_amount
    except Exception as e:
        return f"Error: {e}"

def main():
    print("Simple Currency Converter")
    print("-------------------------")

    # Get user input
    amount = float(input("Enter the amount: "))
    from_currency = input("Enter the source currency code (e.g., USD): ").upper()
    to_currency = input("Enter the target currency code (e.g., EUR): ").upper()

    # Convert currency
    result = convert_currency(amount, from_currency, to_currency)

    # Display the result
    if isinstance(result, float):
        print(f"{amount} {from_currency} is equal to {result:.2f} {to_currency}")
    else:
        print(result)

if __name__ == "__main__":
    main()